// <auto-generated />
using System;
using ControleDeValidades.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeValidades.Migrations
{
    [DbContext(typeof(ControleContext))]
    partial class ControleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ControleDeValidades.Models.MenuAcessos", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id_Opcao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Liberado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Usuario", "Id_Opcao");

                    b.ToTable("menuAcessos");
                });

            modelBuilder.Entity("ControleDeValidades.Models.Opcoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Opcoes");
                });

            modelBuilder.Entity("ControleDeValidades.Models.Produto", b =>
                {
                    b.Property<int>("PRONID_PRO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PROCCODINT")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCDESCR")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCFOR")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCNNUMNF")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCREF")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCSTAT")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCUSRALT")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PROCUSRCAD")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PRODDATALT")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PRODDATCAD")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PRODDATVAL")
                        .HasColumnType("TEXT");

                    b.Property<int>("PRONQUANT")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.HasKey("PRONID_PRO");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ControleDeValidades.Models.Usuarios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Ativo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
